project 'MOSurveyOC.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MOSurveyOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Masonry'
  # Pods for MOSurveyOC
end

target 'MOSurveyOCTests' do
  use_frameworks!
  pod 'OCMock', '~> 3.8.1'
  pod 'OCHamcrest', '~> 8.0'
end

target 'MOSurveyOCUITests' do
  use_frameworks!
end
