project 'MOSurveyOC.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MOSurveyOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Masonry'
  # Pods for MOSurveyOC
end

target 'MOSurveyOCUITests' do
  use_frameworks!
  source 'http://git.code.oa.com/TencentVideoShared/VideoBase.git'
  pod 'OCMock', '0.1.2'
  pod 'OCHamcrest', '0.1.1'
end
